repos:
  - repo: https://github.com/norwoodj/helm-docs
    rev: v1.13.0
    hooks:
      - id: helm-docs
        args:
          # Make the tool search for charts only under the `example-charts` directory
          - --chart-search-root=charts/sddi-ckan
