apiVersion: v2
name: ckan
description: A Helm chart for SDDI enabled CKAN.
type: application

home: https://github.com/tum-gis/sddi-ckan-k8s/
sources:
  - https://github.com/tum-gis/sddi-ckan-k8s/tree/main/sddi-ckan/charts/charts/ckan
  - https://github.com/tum-gis/ckan-docker
  - https://github.com/keitaroinc/docker-ckan

version: 3.1.0
appVersion: "2.1.2"

maintainers:
  - email: b.willenborg@tum.de
    name: Bruno Willenborg
    url: https://www.asg.ed.tum.de/en/gis/our-team/staff/bruno-willenborg/
